FROM eclipse-temurin:17-jdk AS build
COPY . /opt/work
WORKDIR /opt/work
RUN ./mvnw package

#FROM eclipse-temurin:17-jre
FROM eclipse-temurin:17_35-jdk
RUN mkdir /opt/app
WORKDIR /opt/app
COPY --from=build /opt/work/target/*.jar .
EXPOSE 8080
CMD ["java", "-jar", "gh-demo-java.jar"]