name: integration with docker
on: [push]
  
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
      
            - name: docker build
              run: |
                docker build -f Dockerfile.cicd \
                  --tag "${{ steps.meta.outputs.tags }}" \
                  --label "${{ steps.meta.outputs.labels }}" \
                  .
            


