name: integration with docker
on: [push]

permissions: 
  packages: write
  
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}
                labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build
              id: build
              uses: docker/build-push-action@v6
              with:
                load: true
                push: false
                file: Dockerfile.cicd
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            - name: Run Trivy Scanner
              uses: aquasecurity/trivy-action@0.30.0
              with:
                scan-type: image
                scan-ref: ${{ steps.build.outputs.imageid }}
                output: trivy-report.json
                format: json
                exit-code: 0

            - name: Upload Vulnerability Scan Results
              uses: actions/upload-artifact@v4
              with:
                name: trivy-report
                path: trivy-report.json
        
            - name: Fail build on High/Criticial Vulnerabilities
              uses: aquasecurity/trivy-action@0.30.0
              with:
                scan-type: image
                scan-ref: ${{ steps.build.outputs.imageid }}
                format: table
                severity: HIGH,CRITICAL
                ignore-unfixed: true
                exit-code: 1
                skip-setup-trivy: true
                  
            - name: Docker Build
              id: push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                