name: integration with docker
on: [push]

permissions: 
  packages: write
  security-events: write
  
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}
                labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build
              id: build
              uses: docker/build-push-action@v6
              with:
                load: true
                file: Dockerfile.cicd
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            - name: Run Trivy Scanner
              uses: aquasecurity/trivy-action@0.30.0
              with:
                scan-type: image
                scan-ref: ${{ steps.build.outputs.imageid }}
                output: trivy-results.sarif
                format: sarif

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                sarif_file: trivy-results.sarif

            - name: Docker Build
              id: push
              uses: docker/build-push-action@v6
              with:
                push: true
                file: Dockerfile.cicd
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
